---
title: "Untitled"
output: html_document
date: "2024-02-12"
---

```{r}
library(tidyverse)
```

```{r}
data <- read.csv("Data for R and baby.csv")
data
```

```{r}
summary(lm(data = data, Total.Row.Score.C ~ Anteroposterior.1.1 + Anteroposterior + Vertical.1.1 + Vertical.2.1 + Transverse.1 + Crowding.1 + Spacing.1 + Tooth.shape.size..1 + Pan.2..1))
```

```{r}
summary(lm(data = data, Total.Row.Score.C ~ Anteroposterior.1.1 + Anteroposterior + Vertical.1.1 + Vertical.2.1 + Transverse.1 + Spacing.1 + Tooth.shape.size..1 + Pan.2..1))
```

```{r}
summary(lm(data = data, Total.Row.Score.C ~ Anteroposterior.1.1 + Anteroposterior + Vertical.2.1 + Transverse.1 + Spacing.1 + Tooth.shape.size..1 + Pan.2..1))
```

```{r}
summary(lm(data = data, Total.Row.Score.C ~ Anteroposterior.1.1 + Anteroposterior + Vertical.2.1 + Transverse.1 + Tooth.shape.size..1 + Pan.2..1))
```

```{r}
summary(lm(data = data, Total.Row.Score.C ~ Anteroposterior.1.1 + Anteroposterior + Vertical.2.1 + Tooth.shape.size..1 + Pan.2..1))
```

```{r}
summary(lm(data = data, Total.Row.Score.C ~ Anteroposterior.1.1 + Anteroposterior + Tooth.shape.size..1 + Pan.2..1))
```

```{r}
lm_pin <- lm(data = data, Total.Row.Score.C ~ Anteroposterior.1.1 + Anteroposterior + Tooth.shape.size..1 + Pan.2..1)
```

```{r}
plot(data = data, Total.Row.Score.C ~ Pan.2.)
```



```{r}
plot(data$Total.Row.Score.A, data$Total.Row.Score.C)
```

```{r}
boxplot(data$Total.Row.Score.C~data$Center)
```

```{r}
boxplot(data$Total.Row.Score.C~data$X)
```


```{r}
y <- c(data$Total.Row.Score.A, data$Total.Row.Score.B, data$Total.Row.Score.C)
x <- c()
for (i in c(8, 12, 16)) {
  for (j in c(0:122)) {
    x <- append(x, i)
  }
}
```

```{r}
boxplot(y~x)
```


```{r}
summary(lm(data = data, Total.Row.Score.C ~ Anterior.cleft.width.1 + c.c..Width.of.the.cleft.at.the.level.of.C.C..1 + m.m..width.of.the.cleft.at.the.level.of.M.M..1 + t.t..Width.of.the.cleft.at.the.level.of.T.T..1 + Arch.lenght..I.T.T..plane.1 + Total.arch.perimeter.1 + Cleft.surface.Total.max))
```

```{r}
plot(data = data, Total.Row.Score.B ~ Cleft.surface.Total.max)
```

```{r}
total <- 0
for (i in c(1:123)) {
  if (data$Total.Row.Score.C[i] > 9) {
    total <- total + 1
  }
}
print(total / 1.23)
```







